-- MySQL Script generated by MySQL Workbench
-- Sat Jun 15 17:33:55 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema aastu-elearning
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aastu-elearning
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aastu-elearning` ;
USE `aastu-elearning` ;

-- -----------------------------------------------------
-- Table `aastu-elearning`.`assignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aastu-elearning`.`assignment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `weight` DOUBLE NOT NULL,
  `content` TEXT NOT NULL,
  `date_given` DATETIME NOT NULL,
  `deadline` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `course_id` (`course_id` ASC) VISIBLE,
  CONSTRAINT `assignment_ibfk_1`
    FOREIGN KEY (`course_id`)
    REFERENCES `aastu-elearning`.`course` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aastu-elearning`.`college`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aastu-elearning`.`college` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aastu-elearning`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aastu-elearning`.`course` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `image` TEXT NULL DEFAULT NULL,
  `year` INT NOT NULL,
  `semester` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `department_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `department_id` (`department_id` ASC) VISIBLE,
  CONSTRAINT `course_ibfk_1`
    FOREIGN KEY (`department_id`)
    REFERENCES `aastu-elearning`.`department` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aastu-elearning`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aastu-elearning`.`department` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `college_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `college_id` (`college_id` ASC) VISIBLE,
  CONSTRAINT `department_ibfk_1`
    FOREIGN KEY (`college_id`)
    REFERENCES `aastu-elearning`.`college` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aastu-elearning`.`exam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aastu-elearning`.`exam` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` TEXT NOT NULL,
  `weight` DOUBLE NOT NULL,
  `content` TEXT NOT NULL,
  `start_datetime` DATETIME NOT NULL,
  `end_datetime` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `course_id` (`course_id` ASC) VISIBLE,
  CONSTRAINT `exam_ibfk_1`
    FOREIGN KEY (`course_id`)
    REFERENCES `aastu-elearning`.`course` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aastu-elearning`.`instructor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aastu-elearning`.`instructor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `sex` VARCHAR(1) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aastu-elearning`.`instructor_teaches_course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aastu-elearning`.`instructor_teaches_course` (
  `instructor_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`instructor_id`, `course_id`),
  INDEX `course_id` (`course_id` ASC) VISIBLE,
  CONSTRAINT `instructor_teaches_course_ibfk_1`
    FOREIGN KEY (`instructor_id`)
    REFERENCES `aastu-elearning`.`instructor` (`id`),
  CONSTRAINT `instructor_teaches_course_ibfk_2`
    FOREIGN KEY (`course_id`)
    REFERENCES `aastu-elearning`.`course` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aastu-elearning`.`material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aastu-elearning`.`material` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `path` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `course_id` (`course_id` ASC) VISIBLE,
  CONSTRAINT `material_ibfk_1`
    FOREIGN KEY (`course_id`)
    REFERENCES `aastu-elearning`.`course` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aastu-elearning`.`submitted_assignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aastu-elearning`.`submitted_assignment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `path` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL,
  `assignment_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `assignment_id` (`assignment_id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `unique_assignment_user` USING BTREE (`assignment_id`, `user_id`) VISIBLE,
  CONSTRAINT `submitted_assignment_ibfk_1`
    FOREIGN KEY (`assignment_id`)
    REFERENCES `aastu-elearning`.`assignment` (`id`),
  CONSTRAINT `submitted_assignment_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `aastu-elearning`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aastu-elearning`.`submitted_exam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aastu-elearning`.`submitted_exam` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `exam_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `exam_id` (`exam_id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `unique_exam_user` (`exam_id` ASC, `user_id` ASC) VISIBLE,
  CONSTRAINT `submitted_exam_ibfk_1`
    FOREIGN KEY (`exam_id`)
    REFERENCES `aastu-elearning`.`exam` (`id`),
  CONSTRAINT `submitted_exam_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `aastu-elearning`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aastu-elearning`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aastu-elearning`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `sex` VARCHAR(1) NOT NULL,
  `year` INT NOT NULL,
  `semester` INT NOT NULL,
  `section` VARCHAR(2) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `college_id` INT NOT NULL,
  `department_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `college_id` (`college_id` ASC) VISIBLE,
  INDEX `department_id` (`department_id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  CONSTRAINT `user_ibfk_1`
    FOREIGN KEY (`college_id`)
    REFERENCES `aastu-elearning`.`college` (`id`),
  CONSTRAINT `user_ibfk_2`
    FOREIGN KEY (`department_id`)
    REFERENCES `aastu-elearning`.`department` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
